

VALID_FIRST_NAME = "Alex"
VALID_LAST_NAME = "Daskalov"
VALID_PHONE_NUMBER = 111111
VALID_EMAIL = "AlexD@gmail.com"
VALID_STARTING_LOCATION = "Sydney"
VALID_ENDING_LOCATION = "Melbourne"
VALID_PACKAGE = 2

